### ISSUE TITLE
config fastgit error 

### ISSUE THREAD

**Issue by JackLovel** [fastgitorg/document#18]
## system
```
win10  X86_64 
```
## error information 
when I enter below command 
```
git protocol.http.allow always
```
error information png 
![图片](https://user-images.githubusercontent.com/19406670/116766240-073bba00-aa5c-11eb-9be8-31d309b76084.png)

**Comment by KevinZonda** [comment]
WIP

**Comment by JackLovel** [comment]
> 
> 
> WIP

thx
