### ISSUE TITLE
[error] i got this problem

### ISSUE THREAD

**Issue by yklydxtt** [fastgitorg/document#30]
After i run git push
![image](https://user-images.githubusercontent.com/52593709/122230460-4333bd00-ceec-11eb-8499-6e2341549d6e.png)

**Comment by KevinZonda** [comment]
Please enter your GitHub username and password.
If you enable 2FA, maybe now such operation is not valid.
Refer: https://github.com/FastGitORG/nginx-conf/issues/7

**Comment by yklydxtt** [comment]
> Please enter your GitHub username and password.
> If you enable 2FA, maybe now such operation is not valid.
> Refer: [FastGitORG/nginx-conf#7](https://github.com/FastGitORG/nginx-conf/issues/7)

thanks it's helpful

**Comment by KevinZonda** [comment]
@yklydxtt if u want, welcome try SSH.FASTGIT.ORG, use SSH
