### ISSUE TITLE
不能提交超过 10M 的文件吗

### ISSUE THREAD

**Issue by HenryTSZ** [fastgitorg/document#39]
提交报错

> Enumerating objects: 8, done.
> Counting objects: 100% (8/8), done.
> Delta compression using up to 8 threads
> Compressing objects: 100% (5/5), done.
> Writing objects: 100% (6/6), 11.78 MiB | 1.14 MiB/s, done.
> Total 6 (delta 2), reused 0 (delta 0), pack-reused 0
> error: RPC failed; curl 18 transfer closed with outstanding read data remaining
> send-pack: unexpected disconnect while reading sideband packet
> fatal: the remote end hung up unexpectedly
> Everything up-to-date

**Comment by KevinZonda** [comment]
I have no idea, maybe is our NGX setting?

**Comment by HenryTSZ** [comment]
ok
