### ISSUE TITLE
想知道项目原理

### ISSUE THREAD

**Issue by xljiulang** [fastgitorg/document#43]
很好奇本项目的原理是什么，是以什么方式部署的

**Comment by KevinZonda** [comment]
嗨，
感谢关注 FastGit。FastGit 的核心运行依赖于 Nginx，请参阅存储库 <https://github.com/FastGitORG/nginx-conf>。适用于 Debian 10 的便捷部署脚本请访问 <https://github.com/FastGitORG/nginx-conf/blob/master/install-debian10.sh>。

FastGit FinalEndPoint<sup>TM</sup>的核心原始码开源于 <https://github.com/FastGitORG/cfworker> 与<https://github.com/FastGitORG/FinalEndPoint>。

对于分流，我们使用了 EDNS Client Subnet 技术，具体技术细节请参阅 [RFC7871](https://datatracker.ietf.org/doc/html/rfc7871) 与 [阿里云智能解析](https://help.aliyun.com/document_detail/29730.html)。
