### ISSUE TITLE
大佬，可以增加api.github.com的反代吗

### ISSUE THREAD

**Issue by BrunuhVille** [fastgitorg/document#62]
大佬，可以增加api.github.com的反代吗
感谢大佬

**Comment by KevinZonda** [comment]
可以

**Comment by SJJ-dot** [comment]
大佬 这个代理可以用了吗 @KevinZonda

**Comment by przybylowicz0** [comment]
可以先拿着这个用（deno）： [https://gitapi.moelab.one](https://gitapi.moelab.one)

**Comment by SJJ-dot** [comment]
> 可以先拿着这个用（deno）： https://gitapi.moelab.one

感谢
