### ISSUE TITLE
【Q】下载release的大文件会超时断开

### ISSUE THREAD

**Issue by ZhouYixun** [fastgitorg/document#72]
请问是什么问题?

**Comment by KevinZonda** [comment]
不贴日志不贴信息一律不知道

**Comment by StarOnTheSky** [comment]
哪个链接？

**Comment by ZhouYixun** [comment]
> 哪个链接？ （有可能是因为我那时重启了 nginx

https://download.fastgit.org/SonicCloudOrg/sonic-agent/releases/download/v2.0.0-beta/sonic-agent-v2.0.0-beta-windows_x86_64.zip

**Comment by StarOnTheSky** [comment]
> > 哪个链接？ （有可能是因为我那时重启了 nginx
> 
> https://download.fastgit.org/SonicCloudOrg/sonic-agent/releases/download/v2.0.0-beta/sonic-agent-v2.0.0-beta-windows_x86_64.zip

哦，那我就不知道了
