### ISSUE TITLE
SEC_ERROR_EXPIRED_CERTIFICATE

### ISSUE THREAD

**Issue by Ariza25617** [fastgitorg/document#81]
访问https://raw.fastgit.org时会提示证书已过期。
![image](https://github.com/FastGitORG/document/assets/6499068/1c6ee2b4-3fdb-4fd1-813f-3b56b8b8b66b)

**Comment by StarOnTheSky** [comment]
@Ariza25617 请使用 raw.fgit.ml

**Comment by Ariza25617** [comment]
> @Ariza25617 请使用 raw.fgit.ml

raw.fgit.ml可用，谢谢！
